### PR TITLE
Add PR response data

### PR DESCRIPTION
**Pull request by MattIPv4**
This pull request intends to make the following changes:

 - Return the PR creation response data
 - Document this in the README file

This closes #13 

-----
[View rendered README.md](https://github.com/MattIPv4/octokit-create-pull-request/blob/add-pr-response/README.md)

### CODE REVIEW

**Comment by gr2m** [comment]
Thanks! Could you update the test, too, to make sure we don't break the behavior in future?

https://github.com/gr2m/octokit-create-pull-request/blob/master/test/happy-path-test.js

**Comment by MattIPv4** [comment]
@gr2m Should be good to go now unless any further tests need updating 👍

**Comment by MattIPv4** [comment]
Would be awesome to get this published to npm so that I can make use of it in https://github.com/MattIPv4/js.org-cleanup :D

**Comment by gr2m** [comment]
automation for the win :v:

**Pull request merged**
